package net.sourceforge.mayfly.jdbc;

import net.sourceforge.mayfly.*;

import java.sql.*;
import java.util.*;

public class JdbcConnection implements Connection {

    public Statement createStatement() throws SQLException {
        throw new UnimplementedException();
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return new JdbcPreparedStatement(sql);
    }

    public CallableStatement prepareCall(String sql) throws SQLException {
        throw new UnimplementedException();
    }

    public String nativeSQL(String sql) throws SQLException {
        throw new UnimplementedException();
    }

    public void setAutoCommit(boolean autoCommit) throws SQLException {
        throw new UnimplementedException();
    }

    public boolean getAutoCommit() throws SQLException {
        throw new UnimplementedException();
    }

    public void commit() throws SQLException {
        throw new UnimplementedException();
    }

    public void rollback() throws SQLException {
        throw new UnimplementedException();
    }

    public void close() throws SQLException {
        throw new UnimplementedException();
    }

    public boolean isClosed() throws SQLException {
        throw new UnimplementedException();
    }

    public DatabaseMetaData getMetaData() throws SQLException {
        throw new UnimplementedException();
    }

    public void setReadOnly(boolean readOnly) throws SQLException {
        throw new UnimplementedException();
    }

    public boolean isReadOnly() throws SQLException {
        throw new UnimplementedException();
    }

    public void setCatalog(String catalog) throws SQLException {
        throw new UnimplementedException();
    }

    public String getCatalog() throws SQLException {
        throw new UnimplementedException();
    }

    public void setTransactionIsolation(int level) throws SQLException {
        throw new UnimplementedException();
    }

    public int getTransactionIsolation() throws SQLException {
        throw new UnimplementedException();
    }

    public SQLWarning getWarnings() throws SQLException {
        throw new UnimplementedException();
    }

    public void clearWarnings() throws SQLException {
        throw new UnimplementedException();
    }

    public Statement createStatement(int resultSetType, int resultSetConcurrency)
            throws SQLException {
        throw new UnimplementedException();
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType,
            int resultSetConcurrency) throws SQLException {
        throw new UnimplementedException();
    }

    public CallableStatement prepareCall(String sql, int resultSetType,
            int resultSetConcurrency) throws SQLException {
        throw new UnimplementedException();
    }

    public Map getTypeMap() throws SQLException {
        throw new UnimplementedException();
    }

    public void setTypeMap(Map map) throws SQLException {
        throw new UnimplementedException();
    }

    public void setHoldability(int holdability) throws SQLException {
        throw new UnimplementedException();
    }

    public int getHoldability() throws SQLException {
        throw new UnimplementedException();
    }

    public Savepoint setSavepoint() throws SQLException {
        throw new UnimplementedException();
    }

    public Savepoint setSavepoint(String name) throws SQLException {
        throw new UnimplementedException();
    }

    public void rollback(Savepoint savepoint) throws SQLException {
        throw new UnimplementedException();
    }

    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        throw new UnimplementedException();
    }

    public Statement createStatement(int resultSetType,
            int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        throw new UnimplementedException();
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType,
            int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        throw new UnimplementedException();
    }

    public CallableStatement prepareCall(String sql, int resultSetType,
            int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        throw new UnimplementedException();
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException {
        throw new UnimplementedException();
    }

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
            throws SQLException {
        throw new UnimplementedException();
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames)
            throws SQLException {
        throw new UnimplementedException();
    }

}
